[package]
name = "mev"
version.workspace = true
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["boost", "build", "relay"]
boost = ["mev-boost-rs"]
build = ["mev-build-rs", "reth"]
relay = ["mev-relay-rs"]
# enable to use `minimal` preset instead of `mainnet`
minimal-preset = [
    "mev-boost-rs/minimal-preset",
    "mev-build-rs/minimal-preset",
    "mev-relay-rs/minimal-preset",
    "mev-rs/minimal-preset",
]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

mev-boost-rs = { path = "../../mev-boost-rs", optional = true }
mev-relay-rs = { path = "../../mev-relay-rs", optional = true }
mev-build-rs = { path = "../../mev-build-rs", optional = true }
mev-rs = { path = "../../mev-rs" }

serde = { version = "1.0", features = ["derive"] }

clap = { version = "4.1.4", features = ["derive", "env"] }
eyre = { workspace = true }

ethereum-consensus = { workspace = true }
reth = { workspace = true, optional = true }
