[workspace]
resolver = "2"
members = [
    "bin/mev",
    "bin/utils",
    "mev-boost-rs",
    "mev-relay-rs",
    "mev-build-rs",
    "mev-rs",
]
default-members = ["bin/mev"]

[workspace.package]
version = "0.3.0"

[workspace.dependencies]
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "0919f02435e1b64e27c53931cac8e08edaad5f8b" }
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "0919f02435e1b64e27c53931cac8e08edaad5f8b" }

reth = { git = "https://github.com/paradigmxyz/reth", rev = "6d7cd53ad25f0b79c89fd60a4db2a0f2fe097efe" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "6d7cd53ad25f0b79c89fd60a4db2a0f2fe097efe" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "6d7cd53ad25f0b79c89fd60a4db2a0f2fe097efe" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "6d7cd53ad25f0b79c89fd60a4db2a0f2fe097efe" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "6d7cd53ad25f0b79c89fd60a4db2a0f2fe097efe" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "4e22b9e" }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "4e22b9e" }

eyre = "0.6.8"
futures-util = "0.3.30"
sha2 = "0.10.8"

[patch.crates-io]
c-kzg = { git = "https://github.com/ethereum/c-kzg-4844", tag = "v1.0.1" }
