[workspace]
resolver = "2"
members = [
    "bin/mev",
    "bin/utils",
    "mev-boost-rs",
    "mev-relay-rs",
    "mev-build-rs",
    "mev-rs",
]
default-members = ["bin/mev"]

[workspace.package]
version = "0.3.0"

[workspace.dependencies]
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "2ce2ca4d59ef2985088168b0f69a4a8c4f953241" }
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "2ce2ca4d59ef2985088168b0f69a4a8c4f953241" }

reth = { git = "https://github.com/paradigmxyz/reth", rev = "8e65cb3" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "8e65cb3" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "8e65cb3" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "8e65cb3" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "ca54552" }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "ca54552" }

eyre = "0.6.8"
futures-util = "0.3.30"
sha2 = "0.10.8"

[patch.crates-io]
c-kzg = { git = "https://github.com/ethereum/c-kzg-4844", tag = "v1.0.1" }
libffi-sys = { git = "https://github.com/tov/libffi-rs", rev = "d0704d634b6f3ffef5b6fc7e07fe965a1cff5c7b" }
