[workspace]
resolver = "2"
members = [
    "bin/mev",
    "bin/utils",
    "mev-boost-rs",
    "mev-relay-rs",
    "mev-build-rs",
    "mev-rs",
]
default-members = ["bin/mev"]

[workspace.package]
version = "0.3.0"

[workspace.dependencies]
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "2ce2ca4d59ef2985088168b0f69a4a8c4f953241" }
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "2ce2ca4d59ef2985088168b0f69a4a8c4f953241" }

reth = { git = "https://github.com/paradigmxyz/reth", rev = "5f82993c23164ce8ccdc7bf3ae5085205383a5c8" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "5f82993c23164ce8ccdc7bf3ae5085205383a5c8" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "5f82993c23164ce8ccdc7bf3ae5085205383a5c8" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "5f82993c23164ce8ccdc7bf3ae5085205383a5c8" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "77c1240" }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "77c1240" }

futures = "0.3.21"
tokio = "1.0"
tokio-stream = "0.1.15"
axum = "0.6.4"
hyper = "0.14"
tracing = "0.1"
tracing-subscriber = "0.3"
http = "0.2.7"
url = { version = "2.2.2", default-features = false }

serde_json = "1.0.92"
async-trait = "0.1.53"
serde = "1.0"
thiserror = "1.0.30"
parking_lot = "0.12.1"
toml = "0.8.2"

rayon = "1.8.0"

pin-project = "1.0.12"
backoff = "0.4.0"

eyre = "0.6.8"
futures-util = "0.3.30"
sha2 = "0.10.8"
rand = "0.8.5"

clap = "4.1.4"

[patch.crates-io]
c-kzg = { git = "https://github.com/ethereum/c-kzg-4844", tag = "v1.0.1" }
libffi-sys = { git = "https://github.com/tov/libffi-rs", rev = "d0704d634b6f3ffef5b6fc7e07fe965a1cff5c7b" }
